plugins {
    id 'java-gradle-plugin'
    id 'eclipse'
    id 'maven-publish'
    id 'net.minecraftforge.licenser' version '1.2.0'
    id 'net.minecraftforge.gradleutils' version '[2.3,2.4)'
    id 'com.github.ben-manes.versions' version '0.46.0'
}

version = gradleutils.getTagOffsetBranchVersion('FG_6.0')
logger.lifecycle('Version: ' + version + ' Java: ' + System.getProperty('java.version') + ' JVM: ' + System.getProperty('java.vm.version') + '(' + System.getProperty('java.vendor') + ') Arch: ' + System.getProperty('os.arch'))

changelog {
    from '6.0'
    publishAll = false
}
sourceSets {
    common
    mcp
    patcher
    userdev
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(8)
    withSourcesJar()
}

configurations {
    configureEach {
        exclude group: 'org.ow2.asm'
    }
    mcpImplementation.extendsFrom commonImplementation
    patcherImplementation.extendsFrom commonImplementation
    userdevImplementation.extendsFrom mcpImplementation
    implementation.extendsFrom mcpImplementation, patcherImplementation, userdevImplementation
}

tasks.named('jar', Jar).configure {
    from sourceSets.common.output
    from sourceSets.mcp.output
    from sourceSets.patcher.output
    from sourceSets.userdev.output
}

tasks.named('sourcesJar', Jar).configure {
    from sourceSets.common.allJava
    from sourceSets.mcp.allJava
    from sourceSets.patcher.allJava
    from sourceSets.userdev.allJava
}

repositories {
    mavenLocal()
    maven gradleutils.forgeMaven
    maven {
        name "outlandsReleases"
        url "https://maven.outlands.top/releases"
    }
}

license {
    header = file('HEADER')
    exclude '**/*.properties'
    exclude 'net/minecraftforge/gradle/common/diff/'
    exclude 'net/minecraftforge/gradle/common/util/JavaVersionParser.java'
}

tasks.named('wrapper', Wrapper).configure {
    gradleVersion = '9.2'
    distributionType = Wrapper.DistributionType.ALL
}

dependencies {
    commonImplementation gradleApi()
    commonImplementation 'commons-io:commons-io:2.21.0'
    commonImplementation 'org.apache.commons:commons-lang3:3.20.0'
    commonImplementation 'com.google.code.gson:gson:2.13.2'
    commonImplementation 'com.google.guava:guava:33.5.0-jre'
    commonImplementation 'de.siegmar:fastcsv:2.2.1'
    commonImplementation('top.outlands:artifactural:3.0.4') {
        transitive = false
    }
    commonImplementation('net.minecraftforge:unsafe:0.2.0') {
        transitive = false
    }
    commonImplementation 'org.apache.maven:maven-artifact:3.9.11'
    commonImplementation 'org.apache.httpcomponents.core5:httpcore5:5.3.6'
    commonImplementation 'net.minecraftforge:srgutils:0.5.10'
    commonImplementation 'net.minecraftforge:DiffPatch:2.0.12:all'

    mcpImplementation sourceSets.common.output
    patcherImplementation sourceSets.mcp.output
    patcherImplementation sourceSets.common.output
    userdevImplementation sourceSets.mcp.output
    userdevImplementation sourceSets.common.output

    userdevImplementation 'net.minecraftforge:JarJarMetadata:0.3.19'
    userdevImplementation 'net.minecraftforge:JarJarSelector:0.3.19'
}

gradlePlugin {
    plugins {
        mcp {
            id = 'top.outlands.gradle.mcp'
            implementationClass = 'net.minecraftforge.gradle.mcp.MCPPlugin'
        }
        patcher {
            id = 'top.outlands.gradle.patcher'
            implementationClass = 'net.minecraftforge.gradle.patcher.PatcherPlugin'
        }
        userdev {
            id = 'top.outlands.gradle'
            implementationClass = 'net.minecraftforge.gradle.userdev.UserDevPlugin'
        }
    }
    automatedPublishing = true
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = 'top.outlands.gradle'
            artifactId = 'ForgeGradle'
            version = project.version
            from components.java
        }
    }
    repositories {
        maven {
            name = 'outlandsReleases'
            url = 'https://maven.outlands.top/releases'
            credentials(PasswordCredentials)
            authentication {
                basic(BasicAuthentication)
            }
        }
    }
}
